/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RiskMapRouteImport } from './routes/risk-map'
import { Route as SafetyGuidelinesRouteImport } from './routes/safety-guidelines'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskMapRoute = RiskMapRouteImport.update({
  id: '/risk-map',
  path: '/risk-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyGuidelinesRoute = SafetyGuidelinesRouteImport.update({
  id: '/safety-guidelines',
  path: '/safety-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/report': typeof ReportRoute
  '/risk-map': typeof RiskMapRoute
  '/safety-guidelines': typeof SafetyGuidelinesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/report': typeof ReportRoute
  '/risk-map': typeof RiskMapRoute
  '/safety-guidelines': typeof SafetyGuidelinesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/report': typeof ReportRoute
  '/risk-map': typeof RiskMapRoute
  '/safety-guidelines': typeof SafetyGuidelinesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alerts'
    | '/assistant'
    | '/dashboard'
    | '/insights'
    | '/report'
    | '/risk-map'
    | '/safety-guidelines'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alerts'
    | '/assistant'
    | '/dashboard'
    | '/insights'
    | '/report'
    | '/risk-map'
    | '/safety-guidelines'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alerts'
    | '/assistant'
    | '/dashboard'
    | '/insights'
    | '/report'
    | '/risk-map'
    | '/safety-guidelines'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlertsRoute: typeof AlertsRoute
  AssistantRoute: typeof AssistantRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  ReportRoute: typeof ReportRoute
  RiskMapRoute: typeof RiskMapRoute
  SafetyGuidelinesRoute: typeof SafetyGuidelinesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-map': {
      id: '/risk-map'
      path: '/risk-map'
      fullPath: '/risk-map'
      preLoaderRoute: typeof RiskMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-guidelines': {
      id: '/safety-guidelines'
      path: '/safety-guidelines'
      fullPath: '/safety-guidelines'
      preLoaderRoute: typeof SafetyGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlertsRoute: AlertsRoute,
  AssistantRoute: AssistantRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  ReportRoute: ReportRoute,
  RiskMapRoute: RiskMapRoute,
  SafetyGuidelinesRoute: SafetyGuidelinesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
